/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/healthz": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Liveness + database check */
        get: operations["getHealth"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/packs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Offline pack manifest (latest version per slug) */
        get: operations["listPacks"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/feed": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Published feed items, newest first, cursor-paginated */
        get: operations["listFeed"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/feed/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** One feed item plus its "Soma pamoja" links */
        get: operations["getFeedItem"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/bible/{translation}/{book}/{chapter}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Verses of one chapter, optionally with a parallel translation */
        get: operations["getBibleChapter"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        Error: {
            error: string;
        };
        Health: {
            /** @enum {string} */
            status: "ok" | "degraded";
            /** @enum {string} */
            db: "ok" | "down";
        };
        Pack: {
            /** @example bible-SUV */
            slug: string;
            lang: string;
            version: number;
            url: string;
            /** Format: int64 */
            bytes: number;
            sha256: string;
        };
        /** @enum {string} */
        FeedKind: "verse" | "egw_quote" | "sabbath_school" | "prophecy" | "hymn" | "health" | "youth" | "devotional" | "sermon" | "audio_bible";
        Media: {
            /** Format: uuid */
            id: string;
            /** @enum {string} */
            kind: "video" | "audio" | "image";
            url: string;
            hls_url?: string;
            /**
             * Format: int64
             * @description Shown as tap-to-load size in data-saver mode.
             */
            bytes?: number;
            duration_s?: number;
        };
        FeedItem: {
            /** Format: uuid */
            id: string;
            kind: components["schemas"]["FeedKind"];
            lang: string;
            kicker: string;
            source?: string;
            body: string;
            /** @example YOHANA 3:16 */
            ref_label?: string;
            alt_lang?: string;
            /** @description Parallel-language text. */
            alt_body?: string;
            media?: components["schemas"]["Media"];
            cta_label?: string;
            cta_target?: string;
            audience?: string[];
            /** Format: date-time */
            publish_at: string;
        };
        FeedLink: {
            /** @enum {string} */
            target: "verse" | "egw_paragraph" | "belief" | "hymn" | "feed_item" | "ss_day" | "course_lesson";
            target_ref: string;
            label: string;
        };
        FeedItemDetail: components["schemas"]["FeedItem"] & {
            links: components["schemas"]["FeedLink"][];
        };
        FeedPage: {
            items: components["schemas"]["FeedItem"][];
            /** @description Language actually served (falls back to en when the requested language has no items). */
            lang: string;
            /** @description Absent on the last page. */
            next_cursor?: string;
        };
        Verse: {
            /** @example JHN.3.16 */
            osis_ref: string;
            verse: number;
            text: string;
            parallel_text?: string;
        };
        BibleChapter: {
            translation: string;
            parallel?: string;
            book: string;
            /** @description Localised to the translation's language when known. */
            book_name?: string;
            chapter: number;
            verses: components["schemas"]["Verse"][];
        };
    };
    responses: {
        /** @description Invalid request */
        BadRequest: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description Not found */
        NotFound: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
    };
    parameters: {
        /** @description BCP 47 language (sw, en, fr). Defaults to sw. */
        Lang: string;
    };
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    getHealth: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Healthy */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Health"];
                };
            };
            /** @description Database unreachable */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Health"];
                };
            };
        };
    };
    listPacks: {
        parameters: {
            query?: {
                /** @description BCP 47 language (sw, en, fr). Defaults to sw. */
                lang?: components["parameters"]["Lang"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Packs available for the language */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        packs: components["schemas"]["Pack"][];
                    };
                };
            };
            400: components["responses"]["BadRequest"];
        };
    };
    listFeed: {
        parameters: {
            query?: {
                /** @description BCP 47 language (sw, en, fr). Defaults to sw. */
                lang?: components["parameters"]["Lang"];
                /** @description Opaque cursor from a previous page's `next_cursor`. */
                cursor?: string;
                /** @description Comma-separated feed kinds to include (default all). */
                kinds?: string;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description A page of feed items */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FeedPage"];
                };
            };
            400: components["responses"]["BadRequest"];
        };
    };
    getFeedItem: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The item */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FeedItemDetail"];
                };
            };
            404: components["responses"]["NotFound"];
        };
    };
    getBibleChapter: {
        parameters: {
            query?: {
                /** @description Second translation code to align verse-by-verse. */
                parallel?: string;
            };
            header?: never;
            path: {
                translation: string;
                /** @description OSIS/USFM book code. */
                book: string;
                chapter: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The chapter */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BibleChapter"];
                };
            };
            404: components["responses"]["NotFound"];
        };
    };
}
